### ISSUE TITLE
Cannot compile under Linux

### ISSUE THREAD

**Issue by jagrme00** [tdegeus/cppcolormap#20]
Hello, 

I have some problems when I try to compile cppcolormap on my Linux machine. On my windows machine everything compiles without errors. Is there a simple solution to fix this issue?
Some of the errors occur several times so I attached only a snippet of them.

Architecture is:
Ubuntu 18.04.5 LTS x86_64

Used package versions:
xtl-0.6.11
xtensor-0.21.3

-----------------------------

```none
/opt/xtensor-win/include/xtensor/xutils.hpp:347:17: note:   no known conversion for argument 1 from ‘<unresolved overloaded function type>’ to ‘xt::fixed_shape<>&’
In file included from /home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/Intensity_To_RGB_Converter.h:22:0,
                 from /home/espu/Desktop/AMADEUS.u/plain_cpp_sources/helper_sources/Intensity_To_RGB_Converter.cpp:1:
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h: In function ‘xt::xtensor<double, 2> cppcolormap::Accent_r(size_t)’:
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h:3144:70: error: could not convert ‘xt::flip<xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag> >(cppcolormap::Accent(size_t)(), 0)’ from ‘void’ to ‘xt::xtensor<double, 2> {aka xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag>}’
 nline xt::xtensor<double,2> Accent_r(size_t N = 8) { return xt::flip(Accent(N), 0); }
                                                             ~~~~~~~~^~~~~~~~~~~~~~
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h: In function ‘xt::xtensor<double, 2> cppcolormap::Dark2_r(size_t)’:
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h:3145:69: error: could not convert ‘xt::flip<xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag> >(cppcolormap::Dark2(size_t)(), 0)’ from ‘void’ to ‘xt::xtensor<double, 2> {aka xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag>}’
 inline xt::xtensor<double,2> Dark2_r(size_t N = 8) { return xt::flip(Dark2(N), 0); }
                                                             ~~~~~~~~^~~~~~~~~~~~~
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h: In function ‘xt::xtensor<double, 2> cppcolormap::Paired_r(size_t)’:
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h:3146:71: error: could not convert ‘xt::flip<xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag> >(cppcolormap::Paired(size_t)(), 0)’ from ‘void’ to ‘xt::xtensor<double, 2> {aka xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag>}’
 line xt::xtensor<double,2> Paired_r(size_t N = 12) { return xt::flip(Paired(N), 0); }
                                                             ~~~~~~~~^~~~~~~~~~~~~~
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h: In function ‘xt::xtensor<double, 2> cppcolormap::Spectral_r(size_t)’:
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h:3147:73: error: could not convert ‘xt::flip<xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag> >(cppcolormap::Spectral(size_t)(), 0)’ from ‘void’ to ‘xt::xtensor<double, 2> {aka xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag>}’
 ne xt::xtensor<double,2> Spectral_r(size_t N = 11) { return xt::flip(Spectral(   ), 0); }
                                                             ~~~~~~~~^~~~~~~~~~~~~~~~~~

home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h: In function ‘xt::xtensor<double, 2> cppcolormap::YellowOrange(size_t)’:
/home/espu/Desktop/AMADEUS.u/plain_cpp_headers/helper_headers/cppcolormap.h:3137:24: error: no match for ‘operator/’ (operand types are ‘xt::xtensor<double, 2> {aka xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag>}’ and ‘double’)
     return interp(data / 255.0, N);
```

-----------------------------

**Comment by tdegeus** [comment]
Hi! Thanks for you report. 

That is strange... I'm trying to reproduce the error, but I'm not getting any error on linux : https://github.com/tdegeus/cppcolormap/pull/21 . Can you detail how your compile, or even provide a minimal example? Is what you paste the beginning of the error message?

**Comment by jagrme00** [comment]
No it's not the beginning of the message(s). There is just too much output to capture all lines from the shell...

I'll write a minimal example as soon as I get back home today (approx. 8h). In addition I'll provide my building steps using cmake.

Thanks!

**Comment by tdegeus** [comment]
Great!

**Comment by jagrme00** [comment]
Here comes my minimal example (see attached zip-archive at the end of this post).

With respect to the structure of the zip-archive my shell commands are as following:

`cd <dir_path>/Minimal_Example/build`
`sudo cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH="/opt/xtl-0.6.11;/opt/xtensor-0.21.3" ..`
`sudo make`

xtensor and xtl are were built from sources and are installed under /opt/. I downloaded them from their GitHub repos:

https://github.com/xtensor-stack/xtl/tree/0.6.11
https://github.com/xtensor-stack/xtensor/tree/0.21.3

The cmake version is 3.10.2.

----------------------------
main.cpp
```
#include <xtensor/xtensor.hpp>
#include "plain_cpp_headers/helper_headers/cppcolormap.h"

int main()
{
    double rgbArray[3];
    static const xt::xtensor<double, 2Ui64> colorMapTensor = cppcolormap::colormap("winter", 255);


    rgbArray[0] = colorMapTensor(10, 0);
    rgbArray[1] = colorMapTensor(10, 1);
    rgbArray[2] = colorMapTensor(10, 2);


    return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.8)

include_directories(plain_cpp_headers)

include_directories("/opt/xtl-0.6.11/include")
include_directories("/opt/xtensor-0.21.3/include")
[Minimal_Example.zip](https://github.com/tdegeus/cppcolormap/files/5056764/Minimal_Example.zip)


project("Minimal_Example")

set(CMAKE_CXX_STANDARD          11 )
set(CMAKE_CXX_STANDARD_REQUIRED ON )

add_executable(Minimal_Example main.cpp)
```

[Minimal_Example.zip](https://github.com/tdegeus/cppcolormap/files/5056766/Minimal_Example.zip)

**Comment by tdegeus** [comment]
Thanks. xtensor requires C++14, could you try with `set(CMAKE_CXX_STANDARD 14)`?

**Comment by jagrme00** [comment]
What a fast reply! 👍 

It seems to work but there are some remaining errors

-------------------------
/home/espu/Desktop/Minimal_Example/main.cpp: In function ‘int main()’:
/home/espu/Desktop/Minimal_Example/main.cpp:7:38: error: unable to find numeric literal operator ‘operator""Ui64’
     static const xt::xtensor<double, 2Ui64> colorMapTensor = cppcolormap::colormap("winter", 255);
                                      ^~~~~
/home/espu/Desktop/Minimal_Example/main.cpp:7:43: error: template argument 2 is invalid
     static const xt::xtensor<double, 2Ui64> colorMapTensor = cppcolormap::colormap("winter", 255);
                                           ^
/home/espu/Desktop/Minimal_Example/main.cpp:7:97: error: cannot convert ‘xt::xtensor<double, 2> {aka xt::xtensor_container<xt::uvector<double, std::allocator<double> >, 2, (xt::layout_type)1, xt::xtensor_expression_tag>}’ to ‘const int’ in initialization
 ::xtensor<double, 2Ui64> colorMapTensor = cppcolormap::colormap("winter", 255);
                                                                              ^
/home/espu/Desktop/Minimal_Example/main.cpp:10:39: error: ‘colorMapTensor’ cannot be used as a function
     rgbArray[0] = colorMapTensor(10, 0);
                                       ^
/home/espu/Desktop/Minimal_Example/main.cpp:11:39: error: ‘colorMapTensor’ cannot be used as a function
     rgbArray[1] = colorMapTensor(10, 1);
                                       ^
/home/espu/Desktop/Minimal_Example/main.cpp:12:39: error: ‘colorMapTensor’ cannot be used as a function
     rgbArray[2] = colorMapTensor(10, 2);
                                       ^
-------------------------

Can I use "double" instead of "Ui64" and is there another way existing for tensor-indexing?

**Comment by tdegeus** [comment]
Why don't you simply use

```cpp
xt::xtensor<double, 2> colorMapTensor = cppcolormap::colormap("winter", 255);
```

or even 

```cpp
auto colorMapTensor = cppcolormap::colormap("winter", 255);
```
?

**Comment by jagrme00** [comment]
Thats correct. To be honest I don't know why I'm using "Uint64"... maybe I copied it by mistake from somewhere else...
I thought that this is the correct way because I do not have any experience with xtensor at all.

Big thanks for your help and fast replies. Awesome support!

**Comment by tdegeus** [comment]
Great! Happy to help
