### ISSUE TITLE
High-level API

### ISSUE THREAD

**Issue by davidbrochart** [tdegeus/cppcolormap#24]
I was looking for a way to use cppcolormap to convert a 2D xarray into a 3D xarray (the added dimension being RGB), as you would do with matplotlib, e.g.:
```python
# in python using matplotlib
a2 = plt.cm.viridis(a1)
```
I think using `xt::vectorize` is the way to go, but I'm not sure. Or maybe it already exists in this library and I missed it?

**Comment by tdegeus** [comment]
Hi @davidbrochart you are right that that APIs do not align (at least not at the moment). If I understand well at the moment this is the following mapping:

*   `matplotlib.cm.viridis.colors`

    `cppcolormap.viridis()`


*   `n = np.array(matplotlib.cm.viridis.colors).shape[0]`

    `n = cppcolormap.viridis().shape[0]`

*   `np.interp(np.linspace(0, 1, 5), np.linspace(0, 1, n), np.array(matplotlib.cm.viridis.colors)[:, 0])`

    `cppcolormap(5)[:, 0]`

    etc.

Now the bit of matplotlib's API you are talking about is less clear to me. From [here](https://matplotlib.org/3.1.1/tutorials/colors/colormap-manipulation.html):

> The list of colors that comprise the colormap can be directly accessed using the colors property, or it can be accessed indirectly by calling viridis with an array of values matching the length of the colormap. Note that the returned list is in the form of an RGBA Nx4 array, where N is the length of the colormap.

Then three examples are given that, from the text, I would expect to all have the same output:
```python
print('viridis.colors', viridis.colors)
print('viridis(range(12))', viridis(range(12)))
print('viridis(np.linspace(0, 1, 12))', viridis(np.linspace(0, 1, 12)))
```
But in fact, no, the last two give a different output? Could you clarify this maybe to see how we can have cppcolormap do the equivalent? (Or rather, what you'd want it to do!)

Note that, to me, a thing that is confusing in matplotlib's API is that I *can* do `matplotlib.cm.viridis.colors` but I *cannot* do `matplotlib.cm.jet.colors`

**Comment by davidbrochart** [comment]
I'm not sure we should align exactly with matplotlib's API, but at least there should be a function to "colormap" an array, i.e. to transform an array into an RGB array, meaning it would add a dimension of size 3. At the moment I am doing it with loops:
```cpp
// a is a 2D array with integer values in the range [0..255]
auto shape = a.shape();
auto a_cmap = xt::xarray<float>::from_shape({shape[0], shape[1], 3});
auto cmap = cppcolormap::jet();
for (std::size_t i = 0; i < shape[0]; i++)
{
    for (std::size_t j = 0; j < shape[1]; j++)
    {
        auto dst = xt::view(a_cmap, i, j, xt::all());
        auto src = xt::row(cmap, a(i, j));
        dst = src;
    }
}
```
which is not great. It should be possible to use `xt::vectorize`, but it didn't seem to be that easy.

**Comment by tdegeus** [comment]
It's clear what you want. Let me look into it. To do so:

* I guess it would make sense to also be able to map arbitrary data (allowing custom limits). Do you agree?
* Would a free function be an option for you?

**Comment by davidbrochart** [comment]
> It's clear what you want. Let me look into it. To do so:
> 
> * I guess it would make sense to also be able to map arbitrary data (allowing custom limits). Do you agree?

I agree, in the example above that would allow to pass `a` as-is instead of scaling it to `[0..255]`. We should also allow passing `vmin` and `vmax` (in `a`'s range), in case we don't want to map the full range, and in this case values `< vmin` should stick to the "lowest color", and values `> vmax` should stick to the "highest color" color (color saturation). I think that's what you mean by "custom limits".

> * Would a free function be an option for you?

Yes.

**Comment by tdegeus** [comment]
What do you think about this API

```cpp
enum interp_mode
{
    ceil,
    floor,
    mean
};

template <typename S, typename T, size_t N>
inline xt::xtensor<T, N + 1> as_colors(
    const xt::xtensor<S, N>& data,
    const xt::xtensor<T, 2> colors,
    S vmin,
    S vmax,
    const xt::xtensor<T, 1>& set_bad,
    const xt::xtensor<T, 1>& set_under,
    const xt::xtensor<T, 1>& set_over,
    interp_mode mode);
```

with overloads for `xt::xarray` and to default some of the options. 

Actually... Maybe a class could be more useful to untangle all the options:
```cpp
class Colormap
{
public:
    Colormap() = default;

    template <class T>
    Colormap(const T& colors);

    void set_interp_mode(interp_mode mode);

    template <class T>
    void set_bad(const T& colors);

    template <class T>
    void set_over(const T& colors);

    template <class T>
    void set_under(const T& colors);

    template <typename T>
    void set_lim(T vmin, T vmax);

    template <typename T, size_t N>
    xt::xtensor<T, N + 1> map(const xt::xtensor<T, N>& data);
};
```

**Comment by davidbrochart** [comment]
I think the free function is fine. I guess you want `colors` to be passed by reference too? Could you explain what are `set_bad`, `set_under` and `set_over`?

**Comment by tdegeus** [comment]
They handle respectively NaNs, and values outside the limits. Maybe they can be omitted in the free function, and a class could be used for such specific cases

**Comment by davidbrochart** [comment]
But it means the user has to know the color encoding, because these values are in the color domain, right?
I don't think the user should be aware of anything on the color side. For `set_under`, the color should be the same as the one used for `vmin` (the "lowest" color), and for `set_over` the color should be the same as the one used for `vmax` (the "highest" color). For `set_bad` (`NaN`), we should use "no color" (transparent). What do you think?

**Comment by tdegeus** [comment]
I guess it make sense to have a simpler free function without `set_over`, ..., The class then can always be there for that.
