### ISSUE TITLE
Map to terminal colors

### ISSUE THREAD

**Issue by wolfv** [tdegeus/cppcolormap#3]
This is not entirely serious, but could be a cool feature:

Modern terminals can handle 256 colors, which are mapped to some values here: https://jonasjacek.github.io/colors/

This website also has a JSON file.

What I am wondering is wether we could map the (interpolated) RGB colors to terminal colors and then return a vector colormap of terminal colors so that we could plot a heatmap like this with different color schemes:

![](https://files.gitter.im/QuantStack/Lobby/DgO8/Screenshot-from-2018-11-08-12-09-27.png)

**Comment by tdegeus** [comment]
Cool. 

Do you mean you want to construct an interpolated colormap, and then for each color search the closest terminal color?

**Comment by wolfv** [comment]
yep, that would be the idea. 

By the way, you haven't implemented the Viridis colormap yet, right? I think it might require interpolation in the HSV space?

**Comment by tdegeus** [comment]
Do you know how to define the closest color? `min( ( (R - R_i)**2 + (B - B_i)**2 + (G - G_i)**2 )**.5 )`?

No I haven't but that could be done. Do you have a reference where they are defined?

**Comment by wolfv** [comment]
I think that would be the naive approach and it would probably work "well enough" for now... there are probably more involved ideas. E.g. Mathematica defines https://reference.wolfram.com/language/ref/ColorDistance.html (and AFAIK there is an open source implementation in Mathics :) 

Regarding viridis, here is the (nowadays) merged implementation with all the values https://github.com/BIDS/colormap/blob/master/colormaps.py

I don't know if they're RGB but could be!

**Comment by wolfv** [comment]
Seems to be RGB https://matplotlib.org/api/_as_gen/matplotlib.colors.ListedColormap.html

**Comment by tdegeus** [comment]
I will implement the viridis colormaps, but I should then probably step away from the 8bit color definition. There is also no real reason why to stick to this, it's not like a colormap is going to eat up all memory and that things cannot be easily remapped.

I will also include a function to map one colormap to the other (and include the "xterm" colors).

**Comment by wolfv** [comment]
Awesome, this is cool! I think that's all that's needed, I'll try it out right away!

**Comment by tdegeus** [comment]
Fixed the bug (check latest commit). 

Which matching are you using `match` or `math_visual`? There are different tweaks to consider:

* https://stackoverflow.com/questions/1847092/given-an-rgb-value-what-would-be-the-best-way-to-find-the-closest-match-in-the-d/1847112#1847112
* https://en.wikipedia.org/wiki/Color_difference

**Comment by wolfv** [comment]
I just tried the second algorithm mentioned on the wikipedia page under Euclidean and it seems to give slightly nicer results! 

![screenshot from 2018-11-10 13-35-22](https://user-images.githubusercontent.com/885054/48301452-c1d34d00-e4ee-11e8-873e-3260d2263aa5.png)

**Comment by wolfv** [comment]
The other one was your match_visual ...

We could refactor the match function to take an additional algorithm selection enum?

**Comment by tdegeus** [comment]
Yes, let's do that. Do you want to create a PR?

**Comment by wolfv** [comment]
working on it!

>

**Comment by wolfv** [comment]
It has worked out quite nicely:

![screenshot from 2018-11-11 14-16-00](https://user-images.githubusercontent.com/885054/48313413-712a2580-e5bc-11e8-9b56-ad749fa0dd18.png)
![screenshot from 2018-11-11 14-15-52](https://user-images.githubusercontent.com/885054/48313414-712a2580-e5bc-11e8-89d4-2e40870f5fe1.png)
![screenshot from 2018-11-11 14-15-40](https://user-images.githubusercontent.com/885054/48313415-712a2580-e5bc-11e8-94bc-9ed24d13cd82.png)
![screenshot from 2018-11-11 14-15-31](https://user-images.githubusercontent.com/885054/48313416-71c2bc00-e5bc-11e8-8fad-e81a0bc37514.png)

**Comment by wolfv** [comment]
Except that I came to the realisation that it would probably be better to have a real color map for xterm because otherwise, some data might get "swallowed" as there are no color steps or they are not distinguishable enough. But as an experiment and demo this is awesome :)

**Comment by tdegeus** [comment]
Very nice! Looks cool.

I see the problem of not very precise. But I guess that is quite acceptable for such a feature. Once you want to be precise you can always generate a more precise rendering.
